import Head from "next/head";
import FooterComponet from "../components/footer";
import HeaderComponent from "../components/header";
import WavesComponent from "../components/waves";
import styles from "../styles/Home.module.scss";
import AboutComponent from "../components/about";
import { useState } from "react";
import HomeComponent from "../components/home";

function chooseCurrentPage(current_page){
  switch (current_page) {
    case "home":
      return (<HomeComponent />)
    case "about":
      return (<AboutComponent/>);
    default:
      return (<HomeComponent />)
  }

}

export default function Home() {
  const [current_page, set_current_page] = useState("home");

  return (
    <div className={styles.container}>
      <Head>
        <title>Bem vindo a Orlla!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/orlla-logo-original.svg" />
      </Head>

      <HeaderComponent set_current_page={set_current_page} />

      <main className={styles.main}>
        {chooseCurrentPage(current_page)}
        <WavesComponent></WavesComponent>
      </main>

      <FooterComponet />
    </div>
  );
}
